import type { TaxRule } from "@/types/tax";
import { makeRule } from "./_helpers";
import { SRC } from "@/lib/tax/sources";
import * as C from "@/lib/tax/constants";

/** Sonderausgaben (§§ 10, 10b EStG). */
export const sonderausgabenRules: TaxRule[] = [
  makeRule({
    id: "so-vorsorge",
    title: "Vorsorgeaufwendungen (Renten-, Kranken-, Pflegeversicherung)",
    category: "sonderausgaben",
    subcategory: "Vorsorge",
    legalBasis: ["§ 10 Abs. 1 Nr. 2, 3, 3a EStG"],
    officialSources: [SRC.estg10],
    plainLanguageExplanation:
      "Beiträge zur Altersvorsorge (gesetzliche Rente, Rürup), Kranken- und Pflegeversicherung sowie weitere Versicherungen sind als Sonderausgaben abziehbar. Die Basis-Kranken- und Pflegeversicherung ist in voller Höhe absetzbar; Altersvorsorgebeiträge seit 2023 zu 100 % (bis zum Höchstbetrag).",
    taxMechanism: "Komplexe Höchstbetragsberechnung. Basiskranken-/Pflegeversicherung unbegrenzt; Altersvorsorge bis Höchstbetrag (orientiert am Höchstbeitrag zur knappschaftlichen RV).",
    eligiblePersonTypes: ["arbeitnehmer", "selbststaendig", "rentner", "ledig", "verheiratet"],
    amountType: "maximum_amount",
    deductibilityStatus: "only_special_expense",
    requiredConditions: ["tatsächlich gezahlte Beiträge"],
    requiredEvidence: ["Beitragsbescheinigungen", "Lohnsteuerbescheinigung"],
    declarationArea: "Anlage Vorsorgeaufwand",
    commonMistakes: ["Erstattete Beiträge nicht gegengerechnet."],
    confidenceLevel: "needs_verification",
    updateStatus: "annual_update_required",
    warningMessages: ["Die jährlichen Höchstbeträge für Altersvorsorgeaufwendungen ändern sich. Bitte amtliche Werte des jeweiligen Jahres prüfen."],
    worthItHint: "Diese Beiträge stehen meist schon in der Lohnsteuerbescheinigung – fast immer lohnend, da hohe Beträge.",
  }),

  makeRule({
    id: "so-kirchensteuer",
    title: "Kirchensteuer",
    category: "sonderausgaben",
    subcategory: "Kirchensteuer",
    legalBasis: ["§ 10 Abs. 1 Nr. 4 EStG"],
    officialSources: [SRC.estg10],
    plainLanguageExplanation:
      "Gezahlte Kirchensteuer ist als Sonderausgabe abziehbar – abzüglich erstatteter Kirchensteuer. Nicht abziehbar ist die Kirchensteuer auf Kapitalerträge (Abgeltungsteuer).",
    taxMechanism: "Sonderausgaben in voller Höhe (gezahlt minus erstattet).",
    eligiblePersonTypes: ["kirchensteuer"],
    amountType: "unlimited_if_eligible",
    unlimitedDeduction: true,
    deductibilityStatus: "only_special_expense",
    requiredEvidence: ["Lohnsteuerbescheinigung / Steuerbescheid Vorjahr"],
    declarationArea: "Anlage Sonderausgaben",
    calculatorKey: "vollAbziehbar",
    userQuestions: [{ id: "betrag", label: "Gezahlte Kirchensteuer (abzgl. Erstattung)", type: "number", unit: "€" }],
    confidenceLevel: "verified",
  }),

  makeRule({
    id: "so-spenden",
    title: "Spenden und Mitgliedsbeiträge",
    category: "sonderausgaben",
    subcategory: "Spenden",
    legalBasis: ["§ 10b Abs. 1 EStG"],
    officialSources: [SRC.estg10b],
    plainLanguageExplanation:
      "Spenden an gemeinnützige, mildtätige oder kirchliche Organisationen sind bis zu 20 % des Gesamtbetrags der Einkünfte als Sonderausgaben abziehbar. Übersteigende Beträge werden vorgetragen.",
    taxMechanism: "Sonderausgaben bis 20 % des Gesamtbetrags der Einkünfte; Spendenvortrag für den Rest.",
    eligiblePersonTypes: ["spenden"],
    amountType: "maximum_amount",
    deductibilityStatus: "only_special_expense",
    percentage: C.SPENDEN_ANTEIL_HOECHST,
    requiredConditions: ["steuerbegünstigter Empfänger", "Zuwendungsbestätigung (bzw. vereinfachter Nachweis bis 300 €)"],
    requiredEvidence: ["Zuwendungsbestätigung", "bei Kleinbeträgen: Kontoauszug"],
    declarationArea: "Anlage Sonderausgaben",
    calculatorKey: "spenden",
    userQuestions: [{ id: "betrag", label: "Summe der Spenden", type: "number", unit: "€" }],
    commonMistakes: ["Parteispenden falsch eingeordnet (dort zusätzlich Steuerermäßigung nach § 34g EStG).", "Sachspenden ohne Wertnachweis."],
    confidenceLevel: "verified",
  }),

  makeRule({
    id: "so-kinderbetreuung",
    title: "Kinderbetreuungskosten",
    category: "sonderausgaben",
    subcategory: "Kinder",
    legalBasis: ["§ 10 Abs. 1 Nr. 5 EStG"],
    officialSources: [SRC.estg10],
    plainLanguageExplanation:
      "Kosten für die Betreuung von Kindern (Kita, Tagesmutter, Hort) sind anteilig als Sonderausgaben abziehbar – bis 2024 zwei Drittel (max. 4.000 € je Kind), ab 2025 80 % (max. 4.800 € je Kind).",
    taxMechanism: "Anteiliger Sonderausgabenabzug, Höchstbetrag je Kind.",
    eligiblePersonTypes: ["elternteil", "alleinerziehend"],
    amountType: "partial_deduction",
    deductibilityStatus: "only_special_expense",
    deductibleShare: C.KINDERBETREUUNG_ANTEIL,
    maximumAmount: C.KINDERBETREUUNG_MAX,
    requiredConditions: ["Kind im Haushalt, i. d. R. unter 14 Jahren", "Rechnung", "unbare Zahlung"],
    exclusionCriteria: ["Barzahlung", "Kosten für Verpflegung/Nachhilfe/Sportverein"],
    requiredEvidence: ["Rechnung / Bescheid der Einrichtung", "Überweisungsnachweis"],
    declarationArea: "Anlage Kind",
    calculatorKey: "kinderbetreuung",
    userQuestions: [{ id: "kosten", label: "Betreuungskosten je Kind", type: "number", unit: "€" }],
    commonMistakes: ["Verpflegungsanteil mitgerechnet.", "Bar bezahlt."],
    updateStatus: "annual_update_required",
    confidenceLevel: "verified",
  }),

  makeRule({
    id: "so-schulgeld",
    title: "Schulgeld (Privatschule)",
    category: "sonderausgaben",
    subcategory: "Kinder",
    legalBasis: ["§ 10 Abs. 1 Nr. 9 EStG"],
    officialSources: [SRC.estg10],
    plainLanguageExplanation:
      "Schulgeld für eine anerkannte Privatschule ist zu 30 % als Sonderausgabe abziehbar, höchstens 5.000 € je Kind und Jahr. Kosten für Unterkunft, Betreuung und Verpflegung zählen nicht.",
    taxMechanism: "30 % des Schulgelds, max. 5.000 € je Kind.",
    eligiblePersonTypes: ["elternteil"],
    amountType: "partial_deduction",
    deductibilityStatus: "only_special_expense",
    deductibleShare: C.SCHULGELD_ANTEIL,
    maximumAmount: { 2021: 5000, 2022: 5000, 2023: 5000, 2024: 5000, 2025: 5000, 2026: 5000 },
    requiredConditions: ["Anspruch auf Kindergeld/Kinderfreibetrag", "anerkannte Schule (EU/EWR)"],
    requiredEvidence: ["Schulvertrag", "Zahlungsnachweise", "Aufschlüsselung Schulgeld vs. Verpflegung/Unterkunft"],
    declarationArea: "Anlage Kind",
    calculatorKey: "schulgeld",
    userQuestions: [{ id: "kosten", label: "Schulgeld (ohne Unterkunft/Verpflegung)", type: "number", unit: "€" }],
    confidenceLevel: "verified",
  }),

  makeRule({
    id: "so-unterhalt-exgatte",
    title: "Unterhaltsleistungen an Ex-Partner (Realsplitting)",
    category: "sonderausgaben",
    subcategory: "Unterhalt",
    legalBasis: ["§ 10 Abs. 1a Nr. 1 EStG"],
    officialSources: [SRC.estg10],
    plainLanguageExplanation:
      "Unterhalt an den geschiedenen oder dauernd getrennt lebenden Ehegatten ist bis 13.805 € pro Jahr (zzgl. übernommener Basis-KV/PV-Beiträge) als Sonderausgabe abziehbar – mit Zustimmung des Empfängers (Anlage U), der die Beträge dann versteuern muss.",
    taxMechanism: "Sonderausgabenabzug (Realsplitting) bis 13.805 € + übernommene Basiskranken-/Pflegeversicherung.",
    eligiblePersonTypes: ["verheiratet", "ledig"],
    amountType: "maximum_amount",
    deductibilityStatus: "only_special_expense",
    maximumAmount: { 2021: 13805, 2022: 13805, 2023: 13805, 2024: 13805, 2025: 13805, 2026: 13805 },
    requiredConditions: ["Zustimmung des Empfängers (Anlage U)"],
    requiredEvidence: ["Anlage U", "Zahlungsnachweise"],
    declarationArea: "Anlage U / Sonderausgaben",
    confidenceLevel: "verified",
    warningMessages: ["Alternative: Abzug als außergewöhnliche Belastung nach § 33a (ohne Zustimmung, aber niedrigerer Höchstbetrag) – günstigere Variante prüfen."],
  }),

  makeRule({
    id: "so-pauschbetrag",
    title: "Sonderausgaben-Pauschbetrag",
    category: "sonderausgaben",
    subcategory: "Pauschbeträge",
    legalBasis: ["§ 10c EStG"],
    officialSources: [SRC.estg10c],
    plainLanguageExplanation:
      "Ohne Nachweis berücksichtigt das Finanzamt einen Sonderausgaben-Pauschbetrag von 36 € (Einzelveranlagung) bzw. 72 € (Zusammenveranlagung). Er ist gering und meist schon durch Kirchensteuer/Spenden überschritten.",
    taxMechanism: "Pauschbetrag, automatisch.",
    eligiblePersonTypes: ["ledig", "verheiratet"],
    amountType: "lump_sum",
    deductibilityStatus: "deductible",
    lumpSumAmount: { 2021: C.SONDERAUSGABEN_PAUSCHBETRAG, 2022: C.SONDERAUSGABEN_PAUSCHBETRAG, 2023: C.SONDERAUSGABEN_PAUSCHBETRAG, 2024: C.SONDERAUSGABEN_PAUSCHBETRAG, 2025: C.SONDERAUSGABEN_PAUSCHBETRAG, 2026: C.SONDERAUSGABEN_PAUSCHBETRAG },
    requiredEvidence: ["keine"],
    declarationArea: "automatisch",
    confidenceLevel: "verified",
  }),
];
