import type { TaxRule } from "@/types/tax";
import { makeRule, ALL_YEARS, YEARS_FROM_2023 } from "./_helpers";
import { SRC } from "@/lib/tax/sources";
import * as C from "@/lib/tax/constants";

/**
 * Werbungskosten bei nichtselbständiger Arbeit (§ 9 EStG, Anlage N).
 */
export const werbungskostenRules: TaxRule[] = [
  makeRule({
    id: "wk-arbeitnehmer-pauschbetrag",
    title: "Arbeitnehmer-Pauschbetrag",
    category: "werbungskosten",
    subcategory: "Pauschbeträge",
    legalBasis: ["§ 9a Satz 1 Nr. 1a EStG"],
    officialSources: [SRC.estg9a],
    plainLanguageExplanation:
      "Das Finanzamt zieht bei Arbeitnehmern automatisch einen festen Werbungskosten-Pauschbetrag ab – auch ohne Belege. Eigene Werbungskosten lohnen sich erst, wenn sie diesen Betrag übersteigen.",
    taxMechanism: "Pauschaler Abzug von den Einnahmen aus nichtselbständiger Arbeit; wird automatisch berücksichtigt.",
    eligiblePersonTypes: ["arbeitnehmer"],
    amountType: "lump_sum",
    deductibilityStatus: "deductible",
    lumpSumAmount: C.ARBEITNEHMER_PAUSCHBETRAG,
    requiredConditions: ["Einkünfte aus nichtselbständiger Arbeit"],
    requiredEvidence: ["Keine – wird automatisch gewährt"],
    declarationArea: "Anlage N (automatisch)",
    retroactiveClaimPossible: true,
    retroactiveClaimExplanation: "Wird ohnehin automatisch berücksichtigt; relevant ist nur, ob höhere Einzelkosten geltend gemacht werden.",
    worthItHint:
      "Erst Belege sammeln, wenn Ihre Werbungskosten insgesamt den Pauschbetrag übersteigen. Schon Pendelstrecke + Arbeitsmittel reichen dafür oft aus.",
    updateStatus: "annual_update_required",
    confidenceLevel: "verified",
  }),

  makeRule({
    id: "wk-entfernungspauschale",
    title: "Entfernungspauschale (Pendlerpauschale)",
    category: "werbungskosten",
    subcategory: "Mobilität",
    legalBasis: ["§ 9 Abs. 1 Satz 3 Nr. 4 EStG", "§ 9 Abs. 2 EStG"],
    officialSources: [SRC.estg9Nr4],
    plainLanguageExplanation:
      "Für den Weg zur ersten Tätigkeitsstätte können Sie pro Entfernungskilometer (einfache Strecke) eine Pauschale ansetzen – unabhängig vom Verkehrsmittel.",
    taxMechanism: "Werbungskosten: 0,30 €/km für die ersten 20 km, danach erhöhter Satz; nur die einfache Entfernung, nur Arbeitstage.",
    eligiblePersonTypes: ["arbeitnehmer", "pendler"],
    amountType: "maximum_amount",
    deductibilityStatus: "deductible",
    maximumAmount: { 2021: C.ENTFERNUNG_HOECHSTBETRAG, 2022: C.ENTFERNUNG_HOECHSTBETRAG, 2023: C.ENTFERNUNG_HOECHSTBETRAG, 2024: C.ENTFERNUNG_HOECHSTBETRAG, 2025: C.ENTFERNUNG_HOECHSTBETRAG, 2026: C.ENTFERNUNG_HOECHSTBETRAG },
    requiredConditions: ["Fahrten zwischen Wohnung und erster Tätigkeitsstätte"],
    exclusionCriteria: ["Reine Homeoffice-Tage (für denselben Tag keine Entfernungspauschale)"],
    thresholdLogic:
      "Höchstbetrag 4.500 € pro Jahr – außer bei Nutzung eines eigenen oder zur Nutzung überlassenen Pkw, dann unbegrenzt (mit Nachweis).",
    requiredEvidence: ["Anzahl Arbeitstage", "einfache Entfernung in km", "ggf. Nachweis Pkw-Nutzung bei > 4.500 €"],
    declarationArea: "Anlage N",
    calculatorKey: "entfernungspauschale",
    userQuestions: [
      { id: "entfernungKm", label: "Einfache Entfernung zur Arbeit", type: "number", unit: "km" },
      { id: "arbeitstage", label: "Arbeitstage mit Fahrt zur Arbeit", type: "number", unit: "Tage", helpText: "Nur Tage, an denen Sie tatsächlich zur ersten Tätigkeitsstätte gefahren sind." },
      { id: "eigenerPkw", label: "Nutzung eines eigenen/überlassenen Pkw?", type: "boolean", helpText: "Bei Pkw-Nutzung entfällt der Höchstbetrag von 4.500 €." },
    ],
    interactionWithOtherRules: ["wk-homeoffice", "wk-arbeitnehmer-pauschbetrag"],
    commonMistakes: [
      "Hin- und Rückweg doppelt angesetzt (es zählt nur die einfache Entfernung).",
      "Urlaubs-, Krankheits- und Homeoffice-Tage als Fahrtage angegeben.",
      "Unrealistisch viele Arbeitstage (Finanzamt rechnet i. d. R. mit ca. 220–230 Tagen).",
    ],
    auditRiskLevel: "medium",
    retroactiveClaimPossible: "case_by_case",
    updateStatus: "annual_update_required",
    confidenceLevel: "verified",
    warningMessages: ["Es zählt nur die einfache Entfernung, nicht die Hin- und Rückfahrt."],
  }),

  makeRule({
    id: "wk-homeoffice",
    title: "Homeoffice-Pauschale (Tagespauschale)",
    category: "werbungskosten",
    subcategory: "Arbeiten zu Hause",
    legalBasis: ["§ 4 Abs. 5 Satz 1 Nr. 6c EStG", "§ 9 Abs. 5 EStG"],
    officialSources: [SRC.estg9],
    plainLanguageExplanation:
      "Für jeden Tag, an dem Sie überwiegend zu Hause arbeiten, können Sie eine Tagespauschale ansetzen – ohne ein separates Arbeitszimmer.",
    taxMechanism: "Pauschale je Homeoffice-Tag, gedeckelt auf Jahresbetrag und maximale Tagezahl.",
    eligiblePersonTypes: ["arbeitnehmer", "homeoffice", "selbststaendig", "nebentaetigkeit"],
    amountType: "maximum_amount",
    deductibilityStatus: "deductible",
    lumpSumAmount: C.HOMEOFFICE_PRO_TAG,
    maximumAmount: C.HOMEOFFICE_MAX,
    requiredConditions: ["überwiegend zu Hause ausgeübte Tätigkeit am jeweiligen Tag"],
    thresholdLogic:
      "Bis 2022: 5 €/Tag, max. 600 € (120 Tage). Ab 2023: 6 €/Tag, max. 1.260 € (210 Tage), dauerhaft entfristet.",
    requiredEvidence: ["Aufstellung der Homeoffice-Tage (Eigenbeleg/Kalender)"],
    declarationArea: "Anlage N",
    calculatorKey: "homeofficePauschale",
    userQuestions: [
      { id: "homeofficeTage", label: "Anzahl Tage im Homeoffice", type: "number", unit: "Tage" },
    ],
    interactionWithOtherRules: ["wk-entfernungspauschale", "wk-arbeitszimmer"],
    commonMistakes: [
      "Tagespauschale und Entfernungspauschale für denselben Tag angesetzt.",
      "Mehr als die zulässige Höchstzahl an Tagen angegeben.",
    ],
    auditRiskLevel: "low",
    updateStatus: "annual_update_required",
    confidenceLevel: "verified",
  }),

  makeRule({
    id: "wk-arbeitszimmer",
    title: "Häusliches Arbeitszimmer",
    category: "werbungskosten",
    subcategory: "Arbeiten zu Hause",
    legalBasis: ["§ 4 Abs. 5 Satz 1 Nr. 6b EStG", "§ 9 Abs. 5 EStG"],
    officialSources: [SRC.estg4Abs5, SRC.estg9],
    plainLanguageExplanation:
      "Ein abgeschlossenes, (nahezu) ausschließlich beruflich genutztes Arbeitszimmer kann unter engen Voraussetzungen abgesetzt werden. Seit 2023 gilt: voller Abzug bzw. Jahrespauschale 1.260 € nur noch, wenn das Arbeitszimmer der Mittelpunkt der gesamten Tätigkeit ist.",
    taxMechanism:
      "Ab 2023: Bei Tätigkeitsmittelpunkt voller Kostenabzug oder Jahrespauschale 1.260 €. Sonst nur Tagespauschale (Homeoffice). Bis 2022: bis 1.250 €, wenn kein anderer Arbeitsplatz; unbegrenzt bei Mittelpunkt.",
    eligiblePersonTypes: ["arbeitnehmer", "arbeitszimmer", "selbststaendig"],
    amountType: "maximum_amount",
    deductibilityStatus: "special_case",
    maximumAmount: C.ARBEITSZIMMER_JAHRESPAUSCHALE,
    requiredConditions: ["abgeschlossener, büromäßig genutzter Raum", "(nahezu) ausschließlich berufliche Nutzung"],
    exclusionCriteria: ["Arbeitsecke im Wohnzimmer", "Durchgangszimmer", "gemischte Nutzung"],
    requiredEvidence: ["Grundriss/Flächenanteil", "Kostenaufstellung (Miete, Nebenkosten anteilig)", "Nachweis Mittelpunkt der Tätigkeit"],
    declarationArea: "Anlage N bzw. Anlage EÜR",
    interactionWithOtherRules: ["wk-homeoffice"],
    commonMistakes: [
      "Arbeitsecke statt abgeschlossenem Raum geltend gemacht.",
      "Mittelpunkt der Tätigkeit angenommen, obwohl überwiegend beim Arbeitgeber gearbeitet wird.",
    ],
    auditRiskLevel: "high",
    applicableYears: ALL_YEARS,
    worthItHint: "Wenn das Arbeitszimmer nicht der Mittelpunkt ist, ist meist die Tagespauschale einfacher und günstiger.",
    confidenceLevel: "verified",
    warningMessages: ["Diese Position sollte bei Unsicherheit mit einem Steuerberater oder Lohnsteuerhilfeverein geprüft werden."],
  }),

  makeRule({
    id: "wk-arbeitsmittel",
    title: "Arbeitsmittel (inkl. Computer, Laptop, Werkzeug)",
    category: "werbungskosten",
    subcategory: "Arbeitsmittel",
    legalBasis: ["§ 9 Abs. 1 Satz 3 Nr. 6 EStG", "§ 6 Abs. 2 EStG", "§ 7 EStG"],
    officialSources: [SRC.estg9, SRC.estg6Abs2, SRC.estg7],
    plainLanguageExplanation:
      "Gegenstände, die Sie (nahezu) ausschließlich beruflich nutzen – z. B. Computer, Fachbücher, Werkzeug, Büromöbel –, sind als Arbeitsmittel abziehbar. Bis zur GWG-Grenze sofort, darüber über die Nutzungsdauer (AfA).",
    taxMechanism: "Sofortabzug bis GWG-Grenze (800 € netto); darüber Abschreibung. Computer/Software: Nutzungsdauer 1 Jahr (Sofortabzug) laut BMF.",
    eligiblePersonTypes: ["arbeitnehmer", "fortbildung", "student", "selbststaendig"],
    amountType: "partial_deduction",
    deductibilityStatus: "only_if_work_related",
    requiredConditions: ["berufliche Veranlassung", "ggf. Aufteilung bei gemischter Nutzung"],
    requiredEvidence: ["Rechnung/Quittung", "ggf. Nachweis beruflicher Nutzungsanteil"],
    declarationArea: "Anlage N",
    calculatorKey: "arbeitsmittel",
    userQuestions: [
      { id: "kosten", label: "Anschaffungskosten (brutto)", type: "number", unit: "€" },
      { id: "beruflicherAnteilProzent", label: "Beruflicher Nutzungsanteil", type: "number", unit: "%", helpText: "Bei gemischter Nutzung wird anteilig gekürzt. Ab 90 % beruflich gilt meist voller Abzug." },
    ],
    commonMistakes: [
      "Privat überwiegend genutzte Geräte voll angesetzt.",
      "Teure Geräte sofort statt über AfA abgesetzt (außer Computer).",
    ],
    auditRiskLevel: "medium",
    confidenceLevel: "verified",
  }),

  makeRule({
    id: "wk-fortbildung",
    title: "Fortbildungskosten",
    category: "werbungskosten",
    subcategory: "Bildung",
    legalBasis: ["§ 9 Abs. 1 Satz 1 EStG"],
    officialSources: [SRC.estg9],
    plainLanguageExplanation:
      "Kosten für berufliche Fortbildung (Seminare, Kurse, Fachliteratur, Fahrten, Prüfungsgebühren) sind als Werbungskosten unbegrenzt abziehbar, wenn sie mit Ihrem (angestrebten) Beruf zusammenhängen.",
    taxMechanism: "Werbungskosten in voller Höhe (beruflicher Zusammenhang vorausgesetzt).",
    eligiblePersonTypes: ["arbeitnehmer", "fortbildung", "umschulung"],
    amountType: "unlimited_if_eligible",
    unlimitedDeduction: true,
    deductibilityStatus: "only_if_work_related",
    requiredConditions: ["beruflicher Zusammenhang (Erhalt/Verbesserung beruflicher Kenntnisse)"],
    requiredEvidence: ["Rechnungen", "Teilnahmebescheinigungen", "Fahrtnachweise"],
    declarationArea: "Anlage N",
    calculatorKey: "vollAbziehbar",
    userQuestions: [{ id: "betrag", label: "Summe der Fortbildungskosten", type: "number", unit: "€" }],
    auditRiskLevel: "low",
    confidenceLevel: "verified",
  }),

  makeRule({
    id: "wk-bewerbungskosten",
    title: "Bewerbungskosten",
    category: "werbungskosten",
    subcategory: "Beruf allgemein",
    legalBasis: ["§ 9 Abs. 1 Satz 1 EStG"],
    officialSources: [SRC.estg9],
    plainLanguageExplanation:
      "Kosten der Stellensuche (Bewerbungsmappen, Porto, Fahrten zu Vorstellungsgesprächen, Beglaubigungen) sind Werbungskosten – auch wenn die Bewerbung erfolglos war.",
    taxMechanism: "Werbungskosten in voller Höhe.",
    eligiblePersonTypes: ["arbeitnehmer"],
    amountType: "unlimited_if_eligible",
    unlimitedDeduction: true,
    deductibilityStatus: "only_if_work_related",
    requiredEvidence: ["Belege", "Aufstellung der Bewerbungen/Fahrten"],
    declarationArea: "Anlage N",
    calculatorKey: "vollAbziehbar",
    userQuestions: [{ id: "betrag", label: "Summe der Bewerbungskosten", type: "number", unit: "€" }],
    confidenceLevel: "verified",
  }),

  makeRule({
    id: "wk-reisekosten-verpflegung",
    title: "Verpflegungsmehraufwand (Auswärtstätigkeit)",
    category: "werbungskosten",
    subcategory: "Reisekosten",
    legalBasis: ["§ 9 Abs. 4a EStG"],
    officialSources: [SRC.estg9],
    plainLanguageExplanation:
      "Bei beruflichen Auswärtstätigkeiten können Sie für Verpflegung Pauschalen ansetzen – gestaffelt nach Abwesenheitsdauer. Tatsächliche Essenskosten sind nicht abziehbar.",
    taxMechanism: "Pauschalen: > 8 Std. 14 €, ganztägig 28 € (Inland, seit 2020). An-/Abreisetag je 14 €.",
    eligiblePersonTypes: ["arbeitnehmer", "dienstreisen", "selbststaendig"],
    amountType: "lump_sum",
    deductibilityStatus: "deductible",
    requiredConditions: ["beruflich veranlasste Auswärtstätigkeit", "Abwesenheit > 8 Std."],
    requiredEvidence: ["Reisedaten (Datum, Dauer, Ziel)"],
    declarationArea: "Anlage N",
    calculatorKey: "verpflegungsmehraufwand",
    userQuestions: [
      { id: "tageUeber8h", label: "Tage mit > 8 Std. Abwesenheit (inkl. An-/Abreise)", type: "number", unit: "Tage" },
      { id: "tageGanztags", label: "Tage mit ganztägiger Abwesenheit (24 Std.)", type: "number", unit: "Tage" },
    ],
    commonMistakes: ["Vom Arbeitgeber gestellte Mahlzeiten nicht gekürzt.", "Tatsächliche Restaurantkosten statt Pauschale angesetzt."],
    confidenceLevel: "verified",
  }),

  makeRule({
    id: "wk-doppelte-haushaltsfuehrung",
    title: "Doppelte Haushaltsführung",
    category: "werbungskosten",
    subcategory: "Wohnen/Beruf",
    legalBasis: ["§ 9 Abs. 1 Satz 3 Nr. 5 EStG"],
    officialSources: [SRC.estg9],
    plainLanguageExplanation:
      "Wer aus beruflichen Gründen am Arbeitsort eine Zweitwohnung unterhält und zusätzlich einen eigenen Hausstand am Lebensmittelpunkt hat, kann Unterkunft, Fahrten und Verpflegung (zeitlich begrenzt) absetzen.",
    taxMechanism: "Unterkunftskosten am Beschäftigungsort bis 1.000 €/Monat; Familienheimfahrten; Verpflegung für die ersten 3 Monate.",
    eligiblePersonTypes: ["arbeitnehmer", "doppelte_haushaltsfuehrung"],
    amountType: "maximum_amount",
    maximumAmount: { 2021: 12000, 2022: 12000, 2023: 12000, 2024: 12000, 2025: 12000, 2026: 12000 },
    deductibilityStatus: "special_case",
    requiredConditions: ["eigener Hausstand am Lebensmittelpunkt mit finanzieller Beteiligung", "berufliche Veranlassung der Zweitwohnung"],
    requiredEvidence: ["Mietvertrag Zweitwohnung", "Nachweis Hauptwohnsitz und Kostenbeteiligung"],
    declarationArea: "Anlage N",
    auditRiskLevel: "high",
    commonMistakes: ["Kein eigener Hausstand am Lebensmittelpunkt (nur Zimmer bei den Eltern ohne Kostenbeteiligung)."],
    confidenceLevel: "verified",
    warningMessages: ["Unterkunftskosten am Beschäftigungsort sind auf 1.000 € pro Monat begrenzt."],
  }),

  makeRule({
    id: "wk-berufsverbaende",
    title: "Beiträge zu Berufsverbänden und Gewerkschaften",
    category: "werbungskosten",
    subcategory: "Beruf allgemein",
    legalBasis: ["§ 9 Abs. 1 Satz 3 Nr. 3 EStG"],
    officialSources: [SRC.estg9],
    plainLanguageExplanation: "Beiträge zu Gewerkschaften und Berufsverbänden sind in voller Höhe als Werbungskosten abziehbar.",
    taxMechanism: "Werbungskosten in voller Höhe.",
    eligiblePersonTypes: ["arbeitnehmer"],
    amountType: "unlimited_if_eligible",
    unlimitedDeduction: true,
    deductibilityStatus: "deductible",
    requiredEvidence: ["Beitragsnachweis"],
    declarationArea: "Anlage N",
    calculatorKey: "vollAbziehbar",
    userQuestions: [{ id: "betrag", label: "Jahresbeitrag", type: "number", unit: "€" }],
    confidenceLevel: "verified",
  }),

  makeRule({
    id: "wk-kontofuehrung",
    title: "Kontoführungsgebühren (Pauschale)",
    category: "werbungskosten",
    subcategory: "Beruf allgemein",
    legalBasis: ["§ 9 Abs. 1 Satz 1 EStG", "R 9.1 LStR"],
    officialSources: [SRC.estg9],
    plainLanguageExplanation:
      "Für beruflich veranlasste Kontoführung erkennt das Finanzamt ohne Nachweis eine Pauschale von 16 € pro Jahr an.",
    taxMechanism: "Pauschale 16 €/Jahr (ohne Nachweis); höhere tatsächliche Kosten mit Nachweis.",
    eligiblePersonTypes: ["arbeitnehmer"],
    amountType: "lump_sum",
    deductibilityStatus: "deductible",
    lumpSumAmount: { 2021: 16, 2022: 16, 2023: 16, 2024: 16, 2025: 16, 2026: 16 },
    requiredEvidence: ["keine bis 16 €"],
    declarationArea: "Anlage N",
    confidenceLevel: "verified",
  }),
];
